const STRINGS = {
  no_data: "No data",
  ok: "OK",
  close: "Close",
  editImageCrop: "Edit Image Crop",
  change: "Change",
  confirm_password: "Confirm password",
  new_password: "New password",
  old_password: "Old password",
  profile: "Profile",
  change_password: "Change password",
  update_profile_completed: "Update profile completed",
  update_profile_error: "Update profile error",
  change_avatar: "Change avatar",
  email: "Email",
  email_existed: "This email is existed",
  birthday: "Birthday",
  done_successful: "Done",

  //validate
  email_error: "メールアドレスのフォーマットが正しくありません。",
  fill_username: "ユーザー名を入力してください",
  fill_password: "パスワードを入力してください",
  upload_img_failed: "写真が変更できません。",
  network_error:
    "ネットワークに接続できませんでした。しばらくたってから再度お試しください。",
  server_error:
    "通信エラーが発生しました。しばらく時間をおいて再度接続してください。",
  please_type_address: "住所を入力してください。",
  please_type_password: "パスワードを入力してください。",
  please_type_owner_name: "メールアドレスの名前を入力してください。",
  please_type_phone_number: "電話番号を入力してください。",
  please_type_store_name: "店舗名を入力してください。",
  please_type_title: "タイトルを入力してください。",
  please_type_short_description: "詳細を入力してください。",
  please_fill_required_fields: "必修項目を入力してください。",
  endtime_greater_than_starttime:
    "終了時間が開始時間より小さく設定してください。",
  please_set_image: "映像を設定してください",
  something_wrong: "エラーが発生しました。もう一度やり直してください。",
  this_field_is_required: "本項目は必須です。",

  //common-alert
  confirm_public_common: "公開します。よろしいですか？",
  published_common: "公開が完了しました。",
  register_common: "登録確認-共通",

  confirm_register_common: "登録します。よろしいですか？",
  registered_common: "登録が完了しました。",

  confirm_delete_common: "削除します。よろしいですか？",
  deleted_common: "削除が完了しました。",

  confirm_save_common: "保存します。よろしいですか？",
  saved_common: "保存が完了しました。",

  confirm_cancel_common: "予約をキャンセルします。よろしいですか",
  caceled_common: "予約がキャンセルされました。",
  //filter
  search_by_store: "店舗で検索",
  search_by_rank: "ランクで検索",
  search_place_holder: "ユーザー名・メール・電話番号で検索",
  all: "すべて",
  platinum: "プラチナ",
  vip: "ビップ",
  add_new: "新規作成",
  only_jpg_png: "JPG/PNGのみ",
  smaller_than_2mb: "映像のサイズは２MB以内です。",
  text_confirm_delete_img: "この映像を削除します。よろしいですか。",
  male: "男性",
  female: "女性",
  status: "地位",
  type: "種類",
  add_more_course: "時間・料金を増やす",
  please_check_your_email: "メールをチェックしてください。",
  email_was_not_registered: "メールが登録されていません。",

  //form
  image: "画像",
  title: "タイトル",
  content: "内容",
  config_start_time: "適用期間の設定",
  cancel: "キャンセル",
  save: "保存",
  update: "更新",
  upload: "アップロード",
  delete: "削除",
  delete_success: "削除が完了しました。",
  delete_failed: "削除できません。",
  createdTime: "登録日",
  history: "履歴",
  image_required: "画像",
  delivery_start_time: "配信開始日",
  delivery_end_time: "配信終了日",
  name_slide: "タイトル",
  behavior_click: "クリックした時の動作",
  do_nothing: "何もしない",
  detailed_screen_display: "詳細画面表示",
  detailed_info: "詳細のお知らせ",
  display_web: "指定のWebアドレスを表示",
  staff_name_2: "スタッフ名",
  staff_is_existed: "従業員はすでにシステムに存在しています。",
  phone_is_existed: "電話番号が登録されました。",
  email_is_existed: "メールが登録されました。",

  user_management: "User",
  mypage_management: "マイページ",
  coupon_management: "Coupon",
  store_management: "店舗",
  homepage_management: "Food Category",
  notification_management: "Table",
  review_management: "Income",
  profile_management: "プロフィール管理",
  staff_management: "従業員管理",
  booking_management: "予約管理",
  mng_staff_store: "Staff Manager",

  //user-procceess
  user_name: "ユーザー名",
  password: "パスワード",
  username_placeholder: "ユーザー名を入力してください",
  password_placeholder: "パスワードを入力してください",
  login: "ログイン",
  logout: "Logout",
  register: "ログイン",
  you_forgot_password: "パスワードを忘れた場合",
  login_success: "成功",
  login_failed: "登録できません",
  wrong_username_or_password: "ユーザー名またはパスワードは正しくありません。",
  do_u_want_logout: "ログアウトしますか？",
  password_is_incorrect: "パスワードが正しくない",
  has_booking_please_change: "現在の勤務シフトに予約があります。",

  //user-management
  name: "ユーザー名",
  phone_number: "電話番号",
  phone_number_2: "電話",
  address: "住所",
  gender: "性別",
  store: "店舗",
  rank: "ランク",
  confirm_delete_user: "を削除します。よろしいですか。", //them ten nguoi dung vao dau

  //mypage-management
  config_infor_display_mypage: "マイページに表示される情報の設定",
  image_member: "プロフィール写真",
  image_platinum: "プラチナ写真",
  image_vip: "ビップ写真",

  //coupon-management
  coupon_image: "クーポン画像",
  coupon_title: "タイトル",
  start_date: "開始日",
  end_date: "終了日",
  store_applied: "利用店舗",
  add_new_coupon: "新規作成",
  confirm_delete_coupon: "を削除します。よろしいですか。",
  create_new_coupon: "新クーポン作成",
  input_title_coupont: "タイトルを入力してください。",
  please_input_title: "タイトルを入力してください。",
  please_select_store: "店舗を選択してください。",
  please_select_end_date: "終了時を選択してください。",
  please_select_start_date: "開始時を選択してください。",

  //store-management
  store_list: "店舗一覧",
  stt: "順番",
  store_name: "店舗名",
  open_time: "開店時間",
  close_time: "閉店時間",
  store_owner: "店長",
  confirm: "確認",
  confirm_delete_store: "を削除します。よろしいですか。",
  create_store: "店舗登録",
  longitude: "経度",
  latitude: "緯度",
  description: "詳細",
  sort: "表示順", //並び順
  change_position: "表示順変更",
  store_map: "地図の画像",
  change_position_success: "表示順を変更しました。",
  is_it_ok: "よろしいですか？",

  //homepage-management
  config_infor_display_homepage: "ホームページに表示される情報の設定",
  config_image_slide: "スライド映像の設定",
  config_news: "Food Category",
  information_image: "お知らせの写真",
  short_description: "詳細",
  confirm_delete_news: "を削除します。よろしいですか。",
  create_news: "新規作成",

  //notification-management
  notification_image: "お知らせの画像",
  received_people: "受信者",
  confirm_delete_notification: "を削除します。よろしいですか。",
  create_new_notification: "新規お知らせの作成",
  select_received_people: "配信対象",
  select_users: "受信者指定",
  content_notification: "お知らせの内容",
  send_to_store: "店舗指定",

  //review
  staff: "社員",
  member_id: "会員ID",
  staff_name: "社員名",
  date_remarks: "コメントの日付",
  remarks: "コメント",
  date_service: "利用日",

  create_news_success: "お知らせ作成が完了しました。",
  create_notification_success: "お知らせ作成が完了しました。",
  create_store_success: "店舗追加が完了しました。",
  create_coupon_success: "クーポン作成が完了しました。",

  update_news_success: "お知らせ更新が完了しました。",
  update_notification_success: "お知らせ更新が完了しました。",
  update_store_success: "店舗更新が完了しました。",
  update_coupon_success: "クーポン更新が完了しました。",

  //staff-management
  avatar: "アバター",
  staff_id: "スタッフID",
  working_schedule: "Working_schedule",
  add_new_staff: "従業員追加",
  config_schedule: "毎週の勤務シフト表作成",
  input_time: "時間入力",
  start_time: "開始時間",
  end_time: "終了時間",
  add_staff_successful: "従業員が新しく追加されました",
  add_staff_failed: "従業員の追加が失敗しました",
  update_staff_success: "従業員情報は更新されました",
  update_staff_failed: "従業員情報の更新が失敗しました",
  confirm_delete_staff: "を削除してもよろしいですか？",
  store_1: "所属店舗①",
  store_2: "所属店舗②",
  store_3: "所属店舗③",
  average_score: "平均点",
  procedure_range: "手技範囲",
  self_introduction: "自己紹介",
  duplicate_store: "選択した所属店舗が複製されました。",
  please_select_at_least_1: "店舗を選択してください。",

  //booking
  booking: "予約の新規追加",
  customer_name: "お客様名",
  booking_detail: "予約内容",
  package: "サービスパッケージ",
  date: "日付",
  time: "時間",
  time_is_used: "こちらの時間帯は予約が満員となりました",
  schedule_week: "週",
  schedule_month: "月",
  today: "今日",
  create_booking_success: "予約が成功しました",
  update_booking_success: "予約の変更に成功しました",
  select_time: "時間を選択",
  select_date: "日付を選択",
  no_staff_avaliable: "スタッフがいません",
  monday: "月",
  tuesday: "火",
  wednesday: "水",
  thursday: "木",
  friday: "金",
  saturday: "土",
  sunday: "日",
  cancel_booking: "予約キャンセル内容",

  //month
  january: "一月",
  february: "二月",
  march: "三月",
  april: "四月",
  may: "五月",
  june: "六月",
  july: "七月",
  august: "八月",
  september: "九月",
  october: "十月",
  november: "十一月",
  december: "十二月",

  //slide-setting
  slide_setting: "スライド設定",

  //point-history
  monthly_point_history: "月間ポイント履歴",
  filter_by_time: "年月日で検索",
  grant: "付与",
  point_use: "利用",

  //gacha
  gacha: "抽選会",
  gacha_list: "賞リスト",
  winning_digits: "当選下ケタ数",
  points_awarded: "付与ポイント数",
  award_name: "賞名称",
  this_gacha_is_existed: "抽選は既にシステムに存在します。",

  //combo
  course_setting: "コース設定",
  course_price_setting: "コース・料金設定",
  app_member: "アプリ会員",
  non_member: "非会員",
  list_price: "定価",
  category_title: "カテゴリータイトル",
  description_2: "説明",
  increase_time_and_fees: "時間・料金を増やす",

  //point-reception
  point_reception: "ポイント受付",
  grant_points: "ポイント付与",
  use_points: "ポイント利用",
  time_of_visit: "来店年月日",
  staff_in_charge: "担当スタッフ",
  points: "ポイント数",
  reject: "拒否",
  allocationDate: "ポイント受付日時",
  reject_notice: "ポイント付与を拒否します。",
  grant_notice: "ポイント付与を承認します。",
  use_notice: "ポイント利用を承認します。",
  time_confirm: "取得月日",
  discount_amount_yen: "割引金額（円）",

  //visit-history
  visit_history: "来店履歴",
  visit_point: "来店ポイント",
  review_point: "レビューポイント",
  store_total_points: "店舗合計ポイント",
  lottery_point: "抽選ポイント",
  review_evaluation_score: "レビュー評価点",
  filter: "フィルター",
  total_store_points: "店舗ポイント合計",
  total_points_used: "ポイント利用合計",
  lottery: "抽選",
  display_price: "店舗合計",

  //store-info
  name_of_store: "お店の名前",
  open: "開いた",
  owner_name: "店主",
  available_link: "空き状況のURL",
  QRCode: "QR コード",
  QR_list: "来店ポイント用QRコード",

  //store-staff-account
  store_staff_account: "アカウント管理",

  //store-provide-point
  store_provide_point: "ポイント追加",
  furiganaName: "ふりがな",
  download: "ダウンロード",

  // Staff-manager-schedule
  schedule_adjustment: "スケジュール調整",
  prone: "うつぶせ",
  recovery: "回復",
  recommendation: "オススメ",
  store_limited: "店舗限定",
  time_only: "時間のみ",
  name2: "指名",

  checkin: "出勤",
  checkout: "退勤",
  early: "早",
  during: "中",
  late: "遅",

  //staff-schedule
  online_reservation_reception: "ネット予約受付",
  working_hours: "勤務時間",
  commuting_time: "出勤時間",
  fix: "修正",
  rest: "休憩",
  minute: "分",
  reservation_time: "予約時間",
  course: "コース",
  price: "料金",
  staff2: "スタッフ",
  situation: "状態",
  reservation_list: "予約一覧",
  total: "合計",
  change_working_hours: "勤務時間を変更",
  change_working_hours2: "勤務時間変更",
  holiday: "休み",
  attendance_at_work: "出勤",
  rest2: "休憩する",
  configuration: "確定",
  sure: "確定",
  please_select_a_reception_staff: "受付スタッフを選択してください。",
  correction_of_work_hours: "出勤時間の修正",
  please_select_a_change_time: "変更時間を選択してください。",
  if_you_press_the_attendance_button_you_will_not_be_able_to_change_it:
    "インタバール設定",
  describle_checkin: "ボタンを押した後は、インターバルは変更できない。",
  interval: "インターバル",
  add_staff: "スタッフ追加",
  please_select_your_commute_time: "出勤時間を選択してください。",
  please_select_an_attendance_staff: "出勤スタッフを選択してください。",
  time_change: "時間変更",

  combo_color: "コースカラー",
  is_favourite: "おすすめコース",
  is_prolonged: "コースを延長することはできますか？",
  combo_category: "カテゴリー",

  // staff-booking
  next: "次へ",
  step_1: "選択",
  step_2: "時間",
  step_3: "確認",
  tomorrow: "明日",
  num_user: "お客様人数",
  user_num: (i) => `代表者様(${i}人目)`,
  des_booking_1: "①いつのご予約ですか？",
  des_booking_2: "②何名様ですか？",
  des_booking_3: "⑤まずは、電話番号を聞きます。",
  des_booking_4: "⑥お名前と電話番号をお願い致します。(後で入力してもOK)",
  des_booking_5: "③コースはお決まりですか？",
  des_booking_6:
    "⑥施術中の過ごし方のご希望はありますか？次の4つからお選び下さい。",
  des_booking_7: "④スタッフの指名はありますか？",
  name_user_booking: "お名前",
  head: "頭",
  neck: "首",
  shoulder: "肩",
  spine_back: "背中",
  hand: "うで",
  belt: "腰",
  butt: "お尻",
  thighs: "太もも",
  calf: "ふくらはぎ",
  note_title: "特にほぐしてほしい。箇所を選択してください。（複選可)",

  combo_minute: "コース時間のみを選択(来店時に内容を決めたい方にオススメ)",
  combo_recommend: "オススメセット",
  password_title: "パスワードを入力",
  app_non_member: "非アプリ会員",
  yen: "円",
  combo_all: "自由にセレクト",
  select: "あり",
  no_one: "なし",
  please_choose_combo: "コースを選択してください。",
  please_select_staff: "スタッフを選択してください",
  staff_gender: {
    male: "男性",
    female: "女性",
  },
  num_havent_select_course: (i) => `${i}人目がコースを選択していません`,
  wish_time: "希望時間:",
  select_suggest_time: (i) =>
    `希望日時に1番近い日時を次の${i}つからお選び下さい。`,
  available_time: "利用可能な時間",
  day: "日",
  month: "月",
  year: "年",
  unavailable_user: "ユーザーは存在しません",
  //fixed schedule
  shift_list: "シフト一覧",
  checkin_success: "出勤が成功しました。",
  checkout_success: "退出が成功しました。",
  add_working_hour: "勤務時間の追加",
  please_select_shift: "シフトを選択してください。",
  back: "戻る",
  number_people: "お客様数",
  confirm_book: "ご予約確認",
  confirm_booking_user: (i) => `代表者様のご予約確認 \xa0\xa0 (${i}人目)`,
  confirm_note: "施術中の接客",
  no_suggest_available:
    "適切な予約時間枠はありません。別の予約時間を選択してください。",
  NG_list: "NG リスト",
  feedback: "フィードバック",
  manager_cm: "Food Manager",
  shift: "シフト",
  reason: "理由",

  push_to_staff: "Booking",
  shift_existed: "シフトはすでに存在しました",
  shift_duplicated: "勤務時間が重複しています",
  customer_info: "お客様情報",
  member: "会員",
  NG_designation: "NG指定",
  cancellation_charge: "キャンセル料",
  course_extension: "コース延長",

  canceled_with_contact: "連絡あり",
  cancellation_without_permission: "連絡なし",
  cancellation_at_store: "店舗都合",
  cash_register: "レジ",
  date2: "日付け",
  responsible_person: "担当",
  extension: "延長",

  done: "済",
  situation_booking: {
    order: "命じた",
    done: "完了",
    arrive: "が働いている",
  },

  download_staff_schedule: "Download staff schedule",

  revenue_fixed: "定価",
  revenue_staff: "スタッフの取り分",
  revenue_store: "店の取り分",
  tax: "消費税",

  revenue_fixed_2: "定価（税別）",
  revenue_store_2: "店取り分",
  now: "今すぐ",
  day_book: "希望日",
  hour_book: "希望時間",
  content_course: "コース内容",
  remuneration: "報酬",
  working_hours_2: "勤務時間帯",
  attendance_time: "出勤時刻",
  number_of_customer_service: "接客数",
  number_of_names: "指名数",
  people: "人",
  leave_time: "退勤時刻",
  people_2: "振替",
  next_work_status: "欠勤状況",
  bonus_staff_work: "出勤スタッフの追加",
  staff_name_3: "施術担当",
  day_ordered: "施術日",
  day_assigned: "受付日",
  staff_assigned: "受付担当",

  //staff change history
  type_change: "アクション",
  old_value: "古い内容",
  new_value: "変更内容",
  change_history: "変更履歴",
  checkin_booking: "チェックイン",
  manager_2: "担当者",
  registration_date: "登録日",
  favourite: "お気に入り",
  isAssign: "指名",
  today_comment: "今日のコメント",
  add_combo: "コース追加",
  edit_combo: "コース内容変更",
  search_booking: "検索",
  change_info_customer: "お客様情報を編集する",
  past_medical_history: "お客様情報(疾患や趣味、座り仕事などの情報)",
  des_done_booking: "予約をレジします。よろしいでしょうか。",
  edit_information_customer: "情報を編集する",
  senior_member: "シニア会員",
  non_app_member: "非アプリ会員",
  edit_not_good: "編集",
  bed: "ベッド数",
};

const LOGIC = {
  shiftColor: {
    早: "#FFE1CD",
    中: "#DCE4D4",
    遅: "#CDDDFE",
  },
  day: {
    1: "Monday",
    2: "Tuesday",
    3: "Wednesday",
    4: "Thursday",
    5: "Friday",
    6: "Saturday",
    7: "Sunday",
  },
  dateFormat: "DD/MM/YYYY",
  timeFormat: "DD/MM/YYYY HH:mm",
  currencyFormatter: (e) => {
    return (
      new Intl.NumberFormat("ja-JP", {
        // maximumSignificantDigits: 1,
        style: "currency",
        currency: "JPY",
      })
        .format(e)
        .substring(1) + " 円"
    );
  },
  currencyYenFormatter: (e) => {
    return new Intl.NumberFormat("ja-JP", {
      // maximumSignificantDigits: 1,
      style: "currency",
      currency: "JPY",
    }).format(e);
  },
  actionBookingType: {
    cancel_contact: STRINGS.canceled_with_contact,
    cancel_no_contact: STRINGS.cancellation_without_permission,
    cancel_by_store: STRINGS.cancellation_at_store,
    done: STRINGS.cash_register,
  },
};

export { STRINGS, LOGIC };
